# Generated by Django 4.2.2 on 2024-05-02 18:16

import django.db.models.deletion
from django.db import migrations, models

import purchase_order.utils.misc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                (
                    'po_number',
                    models.CharField(
                        db_index=True,
                        default=purchase_order.utils.misc.generate_crpto_accurate_keys,
                        max_length=8,
                        primary_key=True,
                        serialize=False
                    )
                ),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField(null=True)),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled')],
                        default='pending',
                        max_length=10
                    )
                ),
                ('quality_rating', models.FloatField(null=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('acknowledgement_date', models.DateTimeField(null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
            options={
                'db_table': 'vendor"."purchase_orders',
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(
                check=models.Q(('quality_rating__gte', 1), ('quality_rating__lte', 10)),
                name='quality_rating_range_constrained'
            ),
        ),
    ]
