# Generated by Django 4.2.2 on 2024-05-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
