version: '3.9'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      VENDORSETTINGS_DATABASES: '{"default": {"HOST": "db"}}'
      VENDORSETTINGS_LOCAL_SETTINGS_PATH: 'local/settings.dv.py'
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: vendor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
    driver: local