# Generated by Django 4.2.2 on 2024-05-02 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.core.utils.tokens


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='TokenManager',
            fields=[
                (
                    'token',
                    models.TextField(
                        db_index=True,
                        default=core.core.utils.tokens.generate_auth_token,
                        primary_key=True,
                        serialize=False
                    )
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_tokens',
            },
        ),
    ]
